### ISSUE TITLE
stdin error using it with sublime text 3

### ISSUE THREAD

**Issue by iham** [gforcada/flake8-plone-hasattr#3]
running it from commandline works great but using it via sublime text gives me an stdin error
```
IOError: [Errno 2] No such file or directory: 'stdin' 
```
its about the filename. on the command line you get a string, in sublime you get the file.

this is also a problem with the other plone codeanalysis packages
(flake8-plone-api, flake8-pep3101 and flake8-deprecated)

also noqa check is missing, as i might - bad as i am - use hasattr but handle it by adding '# noqa'

**Comment by iham** [comment]
@gforcada i fixed that by handling support for file vs stdin, as it is done by most of the other flake8 packages.

please release asap, so i can use the packages instead of git-sources

thx!

**Comment by gforcada** [comment]
@iham fixed on version 0.2 (thanks to your patch), would you mind giving it a try?
